image:
  file: .gitpod.Dockerfile

tasks:
  - init: (curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -)&& source $HOME/.poetry/env && poetry config virtualenvs.create false && poetry install -E full
