language: minimal
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - BRANCH=$(git branch| grep \* |cut -d ' ' -f2)
  - GIT_TAG=$(git describe --long --tags --dirty --always)
  - IMAGE_NAME="rootlug/aura-security:${BRANCH}-${GIT_TAG}"
  - docker build -t $IMAGE_NAME .
  - docker run -ti --rm $IMAGE_NAME run_tests
  - docker push $IMAGE_NAME
