language: minimal
services:
  - docker




before_install:
  - BRANCH=$(git branch| grep \* |cut -d ' ' -f2)
  - GIT_TAG=$(git describe --long --tags --dirty --always)
  - DOCKER_REPO="rootlug/aura-security"
  - IMAGE_NAME="${DOCKER_REPO}:${GIT_TAG}"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - build
  - test
  - deploy_prod
  - deploy_dev

jobs:
  include:
    - stage: build
      script:
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME

    - stage: test
      script:
        - mkdir shared && chmod 777 shared
        - docker run -ti -v "$PWD/shared:/shared" --rm $IMAGE_NAME run_tests
        - ls -lah shared/
        - bash <(curl -s https://codecov.io/bash) -f shared/coverage.xml

    - stage: deploy_prod
      if: branch = master
      script:
        - docker pull $IMAGE_NAME
        - docker tag $IMAGE_NAME ${DOCKER_REPO}:latest
        - docker push ${DOCKER_REPO}:latest

    - stage: deploy_dev
      if: branch = dev
      script:
        - docker pull $IMAGE_NAME
        - docker tag $IMAGE_NAME ${DOCKER_REPO}:dev
        - docker push ${DOCKER_REPO}:dev

notifications:
  email:
    on_success: change
